# Generated by Django 5.0.1 on 2024-07-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_farmer_delete_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='K',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='N',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='P',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='humidity',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='ph',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='temperature',
            field=models.FloatField(max_length=15),
        ),
    ]
