# Generated by Django 5.0.1 on 2024-07-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_alter_farmer_k_alter_farmer_n_alter_farmer_p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='rainfall',
            field=models.FloatField(max_length=15),
        ),
    ]
